namespace Nocturne.Abstractions.Genesis.Enums
{
    public static class CardStatusDetails
    {
        public enum ArtifactState
        {
            Draft,
            Approved,
            Generated
        }
        public enum CardType
        {
            Starter,
            Expansion,
            DeckModule,
            Utility,
            System,
            Note
        }

        public enum CardOriginType
        {
            AutoGenerated,
            Riff,
            Starter,
            Imported,
            Migrated,
            System
        }

        public enum CardStatusType
        {
            Draft,
            Review,
            Approved,
            Publish,
            Deprecated,
            Retire,
            Remove,
            Conflict
        }

        public enum CardReviewState
        {
            None,
            SharedReview,
            NeedsChanges,
            Endorsed,
            Disputed
        }

        public enum CardVisibility
        {
            Visible,
            Hidden,
            Ghost,
            SystemOnly,
            Internal
        }

        public enum CardIntentType
        {
            Flavor,
            Lore,
            Mechanic,
            Rule,
            Prompt,
            Hook,
            Conflict,
            Resolution,
            Constraint,
            Catalyst,
            Bridge,
            Anchor,
            None
        }

        public enum CardAuthorityType
        {
            System,
            Builder,
            Contributor,
            Moderator,
            Community,
            Locked
        }

        public enum CardConfidenceLevel
        {
            Unknown,
            Low,
            Medium,
            High,
            Contradictory
        }

        public enum CardScopeType
        {
            Local,
            Regional,
            Global,
            Meta,
            CrossDomain
        }

        public enum CardStabilityType
        {
            Anchor,
            Catalyst,
            Bridge,
            Wildcard,
            Neutral,
            Unstable
        }

        public enum CardEnergyType
        {
            Neutral,
            Light,
            Dark,
            Chaotic,
            Serene,
            Aggressive,
            Whimsical,
            Somber,
            Low
        }

        public enum CardComplexityLevel
        {
            Simple,
            Moderate,
            Complex,
            Advanced,
            Expert
        }

        public enum CardDependencyRole
        {
            Independent,
            Dependent,
            DependencyRoot,
            DependencyLeaf,
            DependencyHub,
            None
        }
    }
}
