<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nocturne.Prism\Nocturne.Prism.csproj" />
      <ProjectReference Include="..\Nocturne.Surface\Nocturne.Surface.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="PrismX.Constellation" Version="1.0.0" />
      <PackageReference Include="PrismX.Crucible" Version="1.0.0" />
    </ItemGroup>

</Project>
