using Nocturne.Abstractions.Genesis;
using Nocturne.Abstractions.Genesis.Enums;
using Nocturne.Genesis.Engine;
using Nocturne.Genesis.Models;

namespace Nocturne.Genesis.Services
{
    internal sealed class GenesisInferenceService : IGenesisInferenceService
    {
        public IGenesisInferenceResult Infer(IGenesisContext context)
        {
            var concrete = (GenesisContext)context;

            var result = new GenesisInferenceResult();

            InferMetadata(concrete, result);
            InferCards(concrete, result);
            BuildStarterDeck(result);

            return result;
        }

        private void InferMetadata(GenesisContext context, GenesisInferenceResult result)
        {
            foreach (var kvp in context.Answers)
            {
                if (kvp.Value is null)
                    continue;

                result.Metadata[kvp.Key] = kvp.Value.ToString() ?? string.Empty;
            }
        }

        private void InferCards(GenesisContext context, GenesisInferenceResult result)
        {
            foreach (var kvp in context.Answers)
            {
                var isLlm = kvp.Key.EndsWith("_llm");
                var baseId = isLlm ? kvp.Key.Replace("_llm", "") : kvp.Key;

                var card = new GenesisCard
                {
                    Id = kvp.Key,
                    Name = baseId.Replace("_", " "),
                    Tags = new List<string> { isLlm ? "llm" : "builder" },
                    Properties = new Dictionary<string, object>
                    {
                        { "source", isLlm ? "llm" : "builder" }
                    },

                    Type = isLlm
                        ? CardStatusDetails.CardType.Utility
                        : CardStatusDetails.CardType.Starter,

                    Origin = isLlm
                        ? CardStatusDetails.CardOriginType.AutoGenerated
                        : CardStatusDetails.CardOriginType.Starter,

                    Status = CardStatusDetails.CardStatusType.Draft,
                    ReviewState = CardStatusDetails.CardReviewState.None,
                    Visibility = CardStatusDetails.CardVisibility.Visible,
                    Intent = CardStatusDetails.CardIntentType.Flavor,

                    Authority = isLlm
                        ? CardStatusDetails.CardAuthorityType.System
                        : CardStatusDetails.CardAuthorityType.Builder,

                    Confidence = CardStatusDetails.CardConfidenceLevel.Unknown,
                    Scope = CardStatusDetails.CardScopeType.Local,
                    Stability = CardStatusDetails.CardStabilityType.Neutral,
                    Energy = CardStatusDetails.CardEnergyType.Neutral,
                    Complexity = CardStatusDetails.CardComplexityLevel.Simple,
                    DependencyRole = CardStatusDetails.CardDependencyRole.Independent
                };

                // Lineage (provenance, versions, fingerprint) is attached later by GenesisEngine.
                result.Cards.Add(card);
            }
        }

        private void BuildStarterDeck(GenesisInferenceResult result)
        {
            result.StarterDeck = new StarterDeck
            {
                Name = "Starter Deck",
                Cards = result.Cards,
                Metadata = result.Metadata
            };
        }
    }
}