using Nocturne.Abstractions.Genesis;
using Nocturne.Abstractions.Genesis.Enums;
using Nocturne.Abstractions.Overlays;
using Nocturne.Genesis.Engine;
using Nocturne.Genesis.Models;

namespace Nocturne.Genesis.Services
{
    internal sealed class GenesisInferenceService : IGenesisInferenceService
    {
        // ORIGINAL SIGNATURE (kept for backward compatibility)
        public IGenesisInferenceResult Infer(IGenesisContext context)
            => Infer(context, null);

        // NEW OVERLAY-AWARE SIGNATURE
        public IGenesisInferenceResult Infer(IGenesisContext context, IOverlayTags? tags = null)
        {
            var concrete = (GenesisContext)context;
            concrete.OverlayTags = tags;

            var result = new GenesisInferenceResult();

            InferMetadata(concrete, result);
            InferCards(concrete, result, tags);
            BuildStarterDeck(result, tags);

            return result;
        }

        private void InferMetadata(GenesisContext context, GenesisInferenceResult result)
        {
            foreach (var kvp in context.Answers)
            {
                if (kvp.Value is null)
                    continue;

                result.Metadata[kvp.Key] = kvp.Value.ToString() ?? string.Empty;
            }
        }

        private void InferCards(GenesisContext context, GenesisInferenceResult result, IOverlayTags? tags)
        {
            foreach (var kvp in context.Answers)
            {
                var isLlm = kvp.Key.EndsWith("_llm");
                var baseId = isLlm ? kvp.Key.Replace("_llm", "") : kvp.Key;

                var card = new GenesisCard
                {
                    Id = kvp.Key,
                    Name = baseId.Replace("_", " "),
                    Tags = new List<string> { isLlm ? "llm" : "builder" },
                    Properties = new Dictionary<string, object>
                    {
                        { "source", isLlm ? "llm" : "builder" }
                    },

                    Type = isLlm
                        ? CardStatusDetails.CardType.Utility
                        : CardStatusDetails.CardType.Starter,

                    Origin = isLlm
                        ? CardStatusDetails.CardOriginType.AutoGenerated
                        : CardStatusDetails.CardOriginType.Starter,

                    Status = CardStatusDetails.CardStatusType.Draft,
                    ReviewState = CardStatusDetails.CardReviewState.None,
                    Visibility = CardStatusDetails.CardVisibility.Visible,
                    Intent = CardStatusDetails.CardIntentType.Flavor,

                    Authority = isLlm
                        ? CardStatusDetails.CardAuthorityType.System
                        : CardStatusDetails.CardAuthorityType.Builder,

                    Confidence = CardStatusDetails.CardConfidenceLevel.Unknown,
                    Scope = CardStatusDetails.CardScopeType.Local,
                    Stability = CardStatusDetails.CardStabilityType.Neutral,
                    Energy = CardStatusDetails.CardEnergyType.Neutral,
                    Complexity = CardStatusDetails.CardComplexityLevel.Simple,
                    DependencyRole = CardStatusDetails.CardDependencyRole.Independent
                };

                // Apply overlay tags to card
                if (tags != null)
                {
                    card.Tags.Add($"tone:{tags.Tone}");
                    card.Tags.Add($"density:{tags.Density}");
                    card.Tags.Add($"risk:{tags.Risk}");
                }

                result.Cards.Add(card);
            }
        }

        private void BuildStarterDeck(GenesisInferenceResult result, IOverlayTags? tags)
        {
            var deck = new StarterDeck
            {
                Name = "Starter Deck"
            };

            foreach (var card in result.Cards)
                deck.Cards.Add(card);

            foreach (var kvp in result.Metadata)
                deck.Metadata[kvp.Key] = kvp.Value;

            if (tags != null)
            {
                deck.Metadata["overlay-tone"] = tags.Tone;
                deck.Metadata["overlay-density"] = tags.Density;
                deck.Metadata["overlay-risk"] = tags.Risk;
            }

            result.StarterDeck = deck;
        }
    }
}