<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nocturne.Abstractions\Nocturne.Abstractions.csproj" />
      <ProjectReference Include="..\Nocturne.Genesis\Nocturne.Genesis.csproj" />
      <ProjectReference Include="..\Nocturne.TestHarness\Nocturne.TestHarness.csproj" />
        <None Include="genesis.config.json" CopyToOutputDirectory="Always" />
        <None Include="prompts\**\*.json" CopyToOutputDirectory="Always" />
        <None Include="concepts\**\*.json" CopyToOutputDirectory="Always" />
        <None Update="concepts\concept_trail_of_blood.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="concepts\concept_cryo_nation.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

    </ItemGroup>
    
    
</Project>
