<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PrismX.Crucible" Version="1.0.0" />
        <PackageReference Include="PrismX.Shared" Version="1.0.0" />
    </ItemGroup>

</Project>