<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nocturne.Catalyst\Nocturne.Catalyst.csproj" />
      <ProjectReference Include="..\Nocturne.Constellation\Nocturne.Constellation.csproj" />
      <ProjectReference Include="..\Nocturne.Lens\Nocturne.Lens.csproj" />
      <ProjectReference Include="..\Nocturne.Prism\Nocturne.Prism.csproj" />
      <ProjectReference Include="..\Nocturne.Pulse\Nocturne.Pulse.csproj" />
    </ItemGroup>

</Project>
