<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nocturne.Abstractions\Nocturne.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="LLM\" />
      <Folder Include="Overlays\Engines\Defaults\" />
      <Folder Include="Validation\LLM\" />
    </ItemGroup>

</Project>
