using Nocturne.Abstractions.Genesis;
using Nocturne.Abstractions.Genesis.Enums;

namespace Nocturne.Genesis.Models
{
    internal sealed class GenesisCard : ICard
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public List<string> Tags { get; set; } = new();
        public Dictionary<string, object> Properties { get; set; } = new();

        public CardStatusDetails.CardType Type { get; set; } = CardStatusDetails.CardType.Starter;
        public CardStatusDetails.CardOriginType Origin { get; set; } = CardStatusDetails.CardOriginType.AutoGenerated;
        public CardStatusDetails.CardStatusType Status { get; set; } = CardStatusDetails.CardStatusType.Draft;
        public CardStatusDetails.CardReviewState ReviewState { get; set; } = CardStatusDetails.CardReviewState.None;
        public CardStatusDetails.CardVisibility Visibility { get; set; } = CardStatusDetails.CardVisibility.Visible;
        public CardStatusDetails.CardIntentType Intent { get; set; } = CardStatusDetails.CardIntentType.Flavor;
        public CardStatusDetails.CardAuthorityType Authority { get; set; } = CardStatusDetails.CardAuthorityType.Builder;
        public CardStatusDetails.CardConfidenceLevel Confidence { get; set; } = CardStatusDetails.CardConfidenceLevel.Unknown;
        public CardStatusDetails.CardScopeType Scope { get; set; } = CardStatusDetails.CardScopeType.Local;
        public CardStatusDetails.CardStabilityType Stability { get; set; } = CardStatusDetails.CardStabilityType.Neutral;
        public CardStatusDetails.CardEnergyType Energy { get; set; } = CardStatusDetails.CardEnergyType.Neutral;
        public CardStatusDetails.CardComplexityLevel Complexity { get; set; } = CardStatusDetails.CardComplexityLevel.Simple;
        public CardStatusDetails.CardDependencyRole DependencyRole { get; set; } = CardStatusDetails.CardDependencyRole.Independent;

        public List<CardVersionInfo> Versions { get; set; } = new();

        IReadOnlyList<string> ICard.Tags => Tags;
        IReadOnlyDictionary<string, object> ICard.Properties => Properties;
    }
}